/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guid.mda;

import org.junit.Test;
import static org.junit.Assert.*;

import java.math.BigInteger;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        // App classUnderTest = new App();
        //                          ^
        // assertNotNull("app should have a greeting",
        //               classUnderTest.getGreeting());
        System.out.println("testAppHasAGreeting method of AppTest class");
        int m = Integer.MAX_VALUE;
        int h = m / 2;
        int g = h - 5;
        System.out.println("MAX_VALUE (2^31-1) = " +
                           Integer.toString(m) +
                           ", 0x" + Integer.toHexString(m));
        System.out.println("   half   value   =  " +
                           Integer.toString(h) +
                           ", 0x" + Integer.toHexString(h) +
                           ", 0b" + Integer.toBinaryString(h));
        int x = -2;
        for(int l=0; l<3; l++) {
          for(int q=0; q<4; q++) {
            for(int i=0; i<5; i++) {
              System.out.println("   " + Integer.toString(x) + ",   \t " + Integer.toHexString(x) + ",  \t " + Integer.toBinaryString(x));
              x += 1;
            }
            x += g + 1;
          }
        }
        System.out.println("   " + Integer.toString(x) + ",   \t " + Integer.toHexString(x) + ",  \t " + Integer.toBinaryString(x));
    }
}
